# Project 08 - Oracle Enterprise SQL Assistant (POC)

## Project Objective

The goal of this project is to extend the Production SQL Assistant developed in Project 07 to work with a real Oracle enterprise database.

Instead of querying a local SQLite database, the assistant now connects to a live Oracle database, dynamically discovers the schema, generates Oracle-compatible SQL, executes it safely, and converts the results into natural language.

This project serves as a Proof of Concept (POC) for integrating LLM-powered SQL Assistants with enterprise databases.

---

# Project Architecture

```text
                User
                  │
                  ▼
         Natural Language Question
                  │
                  ▼
         Oracle Schema Discovery
                  │
                  ▼
        Oracle SQL Generator
                  │
                  ▼
          SQL Validator
                  │
                  ▼
          SQL Executor
                  │
                  ▼
          Oracle Database
                  │
                  ▼
            Query Result
                  │
                  ▼
             LLM Wrapper
                  │
                  ▼
         Natural Language Answer
```

---

# Project Structure

```text
08-Oracle-SQL-Agent-POC/

│── app.py
│── agent.py
│── database.py
│── oracle_config.py
│── schema.py
│── sql_generator.py
│── sql_validator.py
│── sql_executor.py
│── llm.py
│── notes.md
```

---

# Oracle SQL Assistant Workflow

```text
User Question
        │
        ▼
Read Oracle Schema
        │
        ▼
Generate Oracle SQL
        │
        ▼
Validate SQL
        │
        ▼
Execute SQL
        │
        ▼
Fetch Database Rows
        │
        ▼
Generate Natural Language Answer
```

---

# What Changed From Project 07?

Project 07 used:

```text
SQLite Database
```

Project 08 replaced SQLite with:

```text
Oracle Enterprise Database
```

The application architecture remained almost identical.

Only the database layer and SQL generation logic were adapted for Oracle.

---

# Oracle Database Connection

Instead of using SQLite,

the application now connects to Oracle using:

```python
import oracledb
```

Connection details are stored separately inside:

```text
oracle_config.py
```

Configuration includes:

- Host
- Port
- Service Name
- Username
- Password

Separating configuration from application logic makes the project cleaner and easier to maintain.

---

# Oracle Schema Discovery

Instead of hardcoding table names,

the assistant reads metadata directly from Oracle.

Example:

```text
COMPANY

- ID
- COMPANY_ID
- NAME
- SERVICE_PROVIDER_ID
```

Benefits:

- No prompt updates
- Automatically adapts to schema changes
- Suitable for enterprise databases

Implemented in:

```text
schema.py
```

---

# Oracle SQL Generation

The SQL Generator was updated to produce Oracle-compatible SQL.

Example:

SQLite

```sql
LIMIT 5
```

Oracle

```sql
FETCH FIRST 5 ROWS ONLY
```

Prompt Engineering was modified to instruct the LLM to generate Oracle SQL syntax instead of SQLite syntax.

---

# Oracle SQL Validation

The same validation pipeline from Project 07 was reused.

Pipeline:

```text
LLM

↓

Generated SQL

↓

Validator

↓

Safe?

↓

Execute
```

Only read-only SQL statements are allowed.

This protects enterprise databases from accidental modifications.

---

# Enterprise Database

Unlike SQLite, Oracle contains real enterprise data.

Example Tables:

```text
COMPANY
```

```text
SERVICE_PROVIDER
```

```text
AUD_COMPANY
```

The assistant can now answer questions using production-like business data instead of sample records.

---

# Oracle SQL Logging

For debugging and monitoring, the assistant displays:

- Generated SQL
- Rows Returned
- Execution Time

Example:

```text
Question:

How many companies are there?

Generated SQL:

SELECT COUNT(*)
FROM COMPANY

Rows Returned:

1

Execution Time:

10 ms
```

Logging makes it easier to verify SQL generated by the LLM.

---

# Problems Faced

## 1. Oracle SQL Syntax

Initially, the LLM generated SQLite-style SQL.

Example:

```sql
LIMIT 5
```

Oracle expects:

```sql
FETCH FIRST 5 ROWS ONLY
```

Prompt engineering was updated to generate Oracle syntax.

---

## 2. Hallucinated Columns

The LLM generated columns that did not exist.

Example:

```text
AUDITED_TIMESTAMP
```

Actual column:

```text
AUDIT_DATE
```

Lesson:

LLMs are only as accurate as the schema information provided.

---

## 3. Invalid SQL Functions

Initially the LLM generated:

```sql
TOLOWER(...)
```

Oracle uses:

```sql
LOWER(...)
```

Prompt engineering was updated accordingly.

---

## 4. Validator False Positives

Initially the validator blocked queries containing columns such as:

```text
UPDATED_TIMESTAMP
```

because it detected the word:

```text
UPDATE
```

Solution:

Used regular expressions with word boundaries.

Example:

```python
re.search(r"\bUPDATE\b", sql)
```

instead of simple string matching.

---

## 5. Oracle Errors

While testing, several Oracle errors were encountered.

Examples:

```text
ORA-00933
SQL command not properly ended
```

```text
ORA-00904
Invalid Identifier
```

These errors helped improve prompt engineering and SQL validation.

---

# Improvements Implemented

Compared to Project 07, the following improvements were introduced:

- Oracle Database Integration
- Oracle SQL Syntax
- Oracle Schema Discovery
- Enterprise Database Support
- Oracle Error Handling
- Improved Prompt Engineering
- Improved SQL Validation
- Better SQL Logging

---

# Design Principles

Applied:

- Separation of Concerns
- Modular Design
- Code Reuse
- Reusable Components
- Enterprise-Friendly Architecture

Most of the architecture from Project 07 was reused with minimal changes.

---

# Interview Questions

## Why build an Oracle SQL Assistant?

Enterprise applications rarely use SQLite.

Oracle is widely used in banking, finance, healthcare, telecom, and government systems.

This project demonstrates how an LLM can interact with enterprise databases.

---

## What changes were required to support Oracle?

- Oracle database connection
- Oracle SQL syntax
- Oracle schema discovery
- Oracle prompt engineering
- Oracle exception handling

---

## Why is Prompt Engineering different for Oracle?

Different databases use different SQL dialects.

The LLM must be instructed to generate SQL compatible with the target database.

---

## What was the biggest challenge?

The biggest challenge was ensuring the LLM generated valid Oracle SQL instead of SQLite SQL and preventing it from hallucinating table and column names.

---

## Why continue using SQL Validation?

Even with Oracle, LLM-generated SQL should never be executed directly.

Validation ensures that only safe, read-only queries reach the database.

---

# Key Learnings

- Enterprise databases require accurate schema information.
- SQL syntax differs across database engines.
- Prompt engineering must be adapted to the target database.
- LLM-generated SQL should always be validated.
- Logging and error handling are essential in enterprise AI applications.
- Existing architectures can be extended with minimal changes through modular design.

---

# Final Architecture

```text
User
 │
 ▼
Oracle SQL Assistant
 │
 ├── Oracle Database
 ├── Schema Discovery
 ├── SQL Generator
 ├── SQL Validator
 ├── SQL Executor
 └── LLM Wrapper
        │
        ▼
     Final Answer
```

---

# Project Outcome

```text
Oracle Database Connection          ✅
Enterprise Schema Discovery         ✅
Oracle SQL Generation               ✅
Oracle SQL Validation               ✅
Oracle SQL Execution                ✅
Natural Language Response           ✅
Prompt Engineering                  ✅
Enterprise Database Support         ✅
SQL Logging                         ✅
Execution Timing                    ✅
Production-Ready POC                ✅
```

🏆 Successfully extended the Production SQL Assistant to support Oracle Enterprise Database, demonstrating how an LLM-powered SQL Assistant can safely query real enterprise data using Oracle-compatible SQL while maintaining a modular, production-style architecture.